version: '3.1'

services:

  api:
    image: mario21ic/api-flask:latest
    build:
      context: ./
    volumes:
      - ./src/:/apps/
    environment:
      FLASK_APP: api.py
      #FLASK_APP: manage.py
    #command: ["flask", "db", "init"]
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "8080"]
    ports:
      - 80:8080

